# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  # This version uses the box in the Atlas catalogue
  config.vm.box = "CiscoDevNet/devnet-dev-base-vmware"
  # This version uses the local definition of the box
  # config.vm.box = "devnet-dev-base-vmware"
  config.vm.hostname = "devnetvm"
  
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # Look out for this issue https://github.com/mitchellh/vagrant/issues/3083
  config.vm.network "private_network", type: "dhcp"
  
  # Configuring VMware
  config.vm.provider "vmware_fusion" do |vmw|
  # Display the GUI when booting the machine
    vmw.gui = true
  # Customize the amount of memory and CPUs on the VM:
    vmw.vmx["memsize"] = "2048"
    vmw.vmx["numvcpus"] = "2"
  end
  #
    
  config.vm.provision "shell", path: "../devnet-dev-base-common/apt-get-update.sh"
  config.vm.provision "shell", path: "../devnet-dev-base-common/reconfigure-vmware-tools.sh"
  config.vm.provision "shell", path: "../devnet-dev-base-common/cleanup-logs.sh"
  config.vm.provision "shell", path: "../devnet-dev-base-common/zero-disk.sh"
  config.vm.provision "shell", path: "../devnet-dev-base-common/passwd-age.sh"

  # This two step approach to copying files from the host seems sub-optimal
  # but it is all that seems to work for now. See mv command below
  config.vm.provision "file", source: "../devnet-dev-base-common/Desktop/README-base.txt", destination: "~vagrant/README.txt"
  
  config.vm.provision "shell", inline: <<-SHELL
  # Move provisioned files into place
  sudo mv ~vagrant/README.txt ~cisco-devnet/Desktop/README
  # Note that we are using the README filename here as it has a location
  # defined already. See below for current status of efforts to set 
  # desktop locations.
  sudo rm ~cisco-devnet/Desktop/*~
  
  # Tidy up bash history
ir  SHELL

  # Position provisioned files on the desktop. Except that this does not work unless
  # run as the cisco-devnet user, when logged in. TBD
  # config.vm.provision "shell", path: "../devnet-dev-base-common/desktop-locations.sh"
end
