# -*- mode: ruby -*-
# vi: set ft=ruby :
# This Vagrantfile creates a VM with the cisco-devnet user and basic other
# settings, and a basic tool set.
Vagrant.configure(2) do |config|
  # This version uses the box in the Atlas catalogue
  # config.vm.box = "CiscoDevNet/devnet-ubuntu-vmware"
  # This version uses the local definition of the box
  config.vm.box = "devnet-ubuntu-vmware"
  config.vm.hostname = "devnetdev"
  
  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  # Look out for this issue https://github.com/mitchellh/vagrant/issues/3083
  config.vm.network "private_network", type: "dhcp"
  
  # Configuring VMware
  config.vm.provider "vmware_fusion" do |vmw|
  # Display the GUI when booting the machine
    vmw.gui = true
  # Customize the amount of memory and CPUs on the VM:
    vmw.vmx["memsize"] = "2048"
    vmw.vmx["numvcpus"] = "2"
  end
  #
    
  config.vm.provision "shell", path: "../devnet-dev-base-common/apt-get-update.sh"
  # The cloud-init install is only required for VMs targetted to be used within VIRL
  # config.vm.provision "shell", path: "../devnet-dev-base-common/cloud-init.sh"
  config.vm.provision "shell", path: "../devnet-dev-base-common/reconfigure-vmware-tools.sh"
  config.vm.provision "shell", path: "../devnet-dev-base-common/add_cisco-devnet_user.sh"
  config.vm.provision "shell", path: "../devnet-dev-base-common/passwd-age.sh"
  config.vm.provision "shell", path: "../devnet-dev-base-common/hide_login_users.sh"
  config.vm.provision "shell", path: "../devnet-dev-base-common/disable_vagrant_user.sh"

  # Also see http://serverfault.com/questions/565281/how-to-upload-configuration-files-using-the-shell-provider
  # See http://stackoverflow.com/questions/25516462/how-can-i-upload-more-than-one-file-with-vagrant-file-provisioning
  # Which is how come there is no wildcarding used below

  config.vm.provision "file", source: "../devnet-dev-base-common/Desktop/README-dev-base.txt", destination: "~vagrant/Desktop/README"
  
  config.vm.provision "file", source: "../devnet-dev-base-common/Desktop/Chrome.desktop", destination: "~vagrant/Desktop/Chrome.desktop"
  config.vm.provision "file", source: "../devnet-dev-base-common/Desktop/Eclipse-JEE.desktop", destination: "~vagrant/Desktop/Eclipse-JEE.desktop"
  config.vm.provision "file", source: "../devnet-dev-base-common/Desktop/IntelliJ.desktop", destination: "~vagrant/Desktop/IntelliJ.desktop"
  config.vm.provision "file", source: "../devnet-dev-base-common/Desktop/PyCharm.desktop", destination: "~vagrant/Desktop/PyCharm.desktop"
  config.vm.provision "file", source: "../devnet-dev-base-common/Desktop/Terminal.desktop", destination: "~vagrant/Desktop/Terminal.desktop"
  # config.vm.provision "file", source: "../devnet-dev-base-common/Desktop/VMMaestro.desktop", destination: "~vagrant/Desktop/VMMaestro.desktop"
  config.vm.provision "file", source: "../devnet-dev-base-common/Desktop/Wireshark.desktop", destination: "~vagrant/Desktop/Wireshark.desktop"
  
  config.vm.provision "shell", path: "../devnet-dev-base-common/move_permissions_desktop_bin.sh"

  config.vm.provision "shell", path: "../devnet-dev-base-common/install_Chrome.sh"
  config.vm.provision "shell", path: "../devnet-dev-base-common/install_java.sh"
  config.vm.provision "shell", path: "../devnet-dev-base-common/install_eclipse.sh"
  config.vm.provision "shell", path: "../devnet-dev-base-common/install_intellij.sh"
  config.vm.provision "shell", path: "../devnet-dev-base-common/install_pycharm.sh"
  config.vm.provision "shell", path: "../devnet-dev-base-common/install_Wireshark.sh"
  config.vm.provision "shell", inline: <<-SHELL
    # Tidy up bash history
    cat /dev/null > ~/.bash_history && history -c
  SHELL

  config.vm.provision "shell", path: "../devnet-dev-base-common/cleanup-logs.sh"
  config.vm.provision "shell", path: "../devnet-dev-base-common/zero-disk.sh"
end
